# Air-gapped image: everything installs from vendored wheels, no index access.
# Build prep (on a networked machine):  scripts/vendor_wheels.sh
# Base image pinned by digest (tags are mutable); bump deliberately:
#   docker buildx imagetools inspect python:3.13-slim
FROM python:3.13-slim@sha256:8d9d0b8bcf6506481eae4907c18f5e3e7902e629f5f6d684f9e7c32e85e3ddf0

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DCT_HUB_CONFIG=/config/charts-tool.yml

WORKDIR /app

COPY image.lock /tmp/image.lock
COPY wheels/ /tmp/wheels/
COPY dist/dct_hub-*.whl /tmp/
# Every third-party wheel is verified against image.lock (hashes of the
# vendored set, committed; regenerated by scripts/vendor_wheels.sh). The
# first-party dct-hub wheel is built locally and unhashed; its deps are
# already installed from image.lock.
RUN pip install --no-cache-dir --no-index --find-links /tmp/wheels --require-hashes \
      -r /tmp/image.lock \
    && pip install --no-cache-dir --no-index --no-deps '/tmp/dct_hub-*.whl[ha]' \
    && rm -rf /tmp/wheels /tmp/image.lock /tmp/dct_hub-*.whl

RUN useradd --create-home --uid 10001 dcthub \
    && mkdir -p /state \
    && chown -R dcthub:dcthub /state
USER dcthub

# Mount points: the dbt Charts project (boards) and hub state.
#   docker run -v $PWD/charts-tool.yml:/config/charts-tool.yml:ro \
#              -v $PWD/my-project:/project -v dct-hub-data:/state dct-hub
VOLUME ["/state"]

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s \
  CMD ["python", "-c", "import urllib.request,os;urllib.request.urlopen('http://127.0.0.1:8080/healthz', timeout=4)"]

CMD ["sh", "-c", "exec dct-hub --config \"$DCT_HUB_CONFIG\""]
